logging:
  console:
    enabled: 'false'
spring:
  application:
    name: analysis
  main:
    web-application-type: none
analysis:
  number-of-arrays: 5
  array-size: 20
  range-of-numbers:
    min: 0
    max: 100